<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 1.0
// Source: google/devtools/clouderrorreporting/v1beta1/error_stats_service.proto
//   Date: 2016-12-21 23:03:50

namespace google\devtools\clouderrorreporting\v1beta1 {

  class TimedCountAlignment extends \DrSlump\Protobuf\Enum {
    const ERROR_COUNT_ALIGNMENT_UNSPECIFIED = 0;
    const ALIGNMENT_EQUAL_ROUNDED = 1;
    const ALIGNMENT_EQUAL_AT_END = 2;
  }
}
namespace google\devtools\clouderrorreporting\v1beta1 {

  class ErrorGroupOrder extends \DrSlump\Protobuf\Enum {
    const GROUP_ORDER_UNSPECIFIED = 0;
    const COUNT_DESC = 1;
    const LAST_SEEN_DESC = 2;
    const CREATED_DESC = 3;
    const AFFECTED_USERS_DESC = 4;
  }
}
namespace google\devtools\clouderrorreporting\v1beta1 {

  class ListGroupStatsRequest extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $project_name = null;
    
    /**  @var string[]  */
    public $group_id = array();
    
    /**  @var \google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter */
    public $service_filter = null;
    
    /**  @var \google\devtools\clouderrorreporting\v1beta1\QueryTimeRange */
    public $time_range = null;
    
    /**  @var \google\protobuf\Duration */
    public $timed_count_duration = null;
    
    /**  @var int - \google\devtools\clouderrorreporting\v1beta1\TimedCountAlignment */
    public $alignment = null;
    
    /**  @var \google\protobuf\Timestamp */
    public $alignment_time = null;
    
    /**  @var int - \google\devtools\clouderrorreporting\v1beta1\ErrorGroupOrder */
    public $order = null;
    
    /**  @var int */
    public $page_size = null;
    
    /**  @var string */
    public $page_token = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.devtools.clouderrorreporting.v1beta1.ListGroupStatsRequest');

      // OPTIONAL STRING project_name = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "project_name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED STRING group_id = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "group_id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE service_filter = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "service_filter";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter';
      $descriptor->addField($f);

      // OPTIONAL MESSAGE time_range = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "time_range";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\QueryTimeRange';
      $descriptor->addField($f);

      // OPTIONAL MESSAGE timed_count_duration = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "timed_count_duration";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\protobuf\Duration';
      $descriptor->addField($f);

      // OPTIONAL ENUM alignment = 7
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 7;
      $f->name      = "alignment";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\TimedCountAlignment';
      $descriptor->addField($f);

      // OPTIONAL MESSAGE alignment_time = 8
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 8;
      $f->name      = "alignment_time";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\protobuf\Timestamp';
      $descriptor->addField($f);

      // OPTIONAL ENUM order = 9
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 9;
      $f->name      = "order";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\ErrorGroupOrder';
      $descriptor->addField($f);

      // OPTIONAL INT32 page_size = 11
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 11;
      $f->name      = "page_size";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING page_token = 12
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 12;
      $f->name      = "page_token";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <project_name> has a value
     *
     * @return boolean
     */
    public function hasProjectName(){
      return $this->_has(1);
    }
    
    /**
     * Clear <project_name> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function clearProjectName(){
      return $this->_clear(1);
    }
    
    /**
     * Get <project_name> value
     *
     * @return string
     */
    public function getProjectName(){
      return $this->_get(1);
    }
    
    /**
     * Set <project_name> value
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function setProjectName( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <group_id> has a value
     *
     * @return boolean
     */
    public function hasGroupId(){
      return $this->_has(2);
    }
    
    /**
     * Clear <group_id> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function clearGroupId(){
      return $this->_clear(2);
    }
    
    /**
     * Get <group_id> value
     *
     * @param int $idx
     * @return string
     */
    public function getGroupId($idx = NULL){
      return $this->_get(2, $idx);
    }
    
    /**
     * Set <group_id> value
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function setGroupId( $value, $idx = NULL){
      return $this->_set(2, $value, $idx);
    }
    
    /**
     * Get all elements of <group_id>
     *
     * @return string[]
     */
    public function getGroupIdList(){
     return $this->_get(2);
    }
    
    /**
     * Add a new element to <group_id>
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function addGroupId( $value){
     return $this->_add(2, $value);
    }
    
    /**
     * Check if <service_filter> has a value
     *
     * @return boolean
     */
    public function hasServiceFilter(){
      return $this->_has(3);
    }
    
    /**
     * Clear <service_filter> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function clearServiceFilter(){
      return $this->_clear(3);
    }
    
    /**
     * Get <service_filter> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter
     */
    public function getServiceFilter(){
      return $this->_get(3);
    }
    
    /**
     * Set <service_filter> value
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function setServiceFilter(\google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <time_range> has a value
     *
     * @return boolean
     */
    public function hasTimeRange(){
      return $this->_has(5);
    }
    
    /**
     * Clear <time_range> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function clearTimeRange(){
      return $this->_clear(5);
    }
    
    /**
     * Get <time_range> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\QueryTimeRange
     */
    public function getTimeRange(){
      return $this->_get(5);
    }
    
    /**
     * Set <time_range> value
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\QueryTimeRange $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function setTimeRange(\google\devtools\clouderrorreporting\v1beta1\QueryTimeRange $value){
      return $this->_set(5, $value);
    }
    
    /**
     * Check if <timed_count_duration> has a value
     *
     * @return boolean
     */
    public function hasTimedCountDuration(){
      return $this->_has(6);
    }
    
    /**
     * Clear <timed_count_duration> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function clearTimedCountDuration(){
      return $this->_clear(6);
    }
    
    /**
     * Get <timed_count_duration> value
     *
     * @return \google\protobuf\Duration
     */
    public function getTimedCountDuration(){
      return $this->_get(6);
    }
    
    /**
     * Set <timed_count_duration> value
     *
     * @param \google\protobuf\Duration $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function setTimedCountDuration(\google\protobuf\Duration $value){
      return $this->_set(6, $value);
    }
    
    /**
     * Check if <alignment> has a value
     *
     * @return boolean
     */
    public function hasAlignment(){
      return $this->_has(7);
    }
    
    /**
     * Clear <alignment> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function clearAlignment(){
      return $this->_clear(7);
    }
    
    /**
     * Get <alignment> value
     *
     * @return int - \google\devtools\clouderrorreporting\v1beta1\TimedCountAlignment
     */
    public function getAlignment(){
      return $this->_get(7);
    }
    
    /**
     * Set <alignment> value
     *
     * @param int - \google\devtools\clouderrorreporting\v1beta1\TimedCountAlignment $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function setAlignment( $value){
      return $this->_set(7, $value);
    }
    
    /**
     * Check if <alignment_time> has a value
     *
     * @return boolean
     */
    public function hasAlignmentTime(){
      return $this->_has(8);
    }
    
    /**
     * Clear <alignment_time> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function clearAlignmentTime(){
      return $this->_clear(8);
    }
    
    /**
     * Get <alignment_time> value
     *
     * @return \google\protobuf\Timestamp
     */
    public function getAlignmentTime(){
      return $this->_get(8);
    }
    
    /**
     * Set <alignment_time> value
     *
     * @param \google\protobuf\Timestamp $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function setAlignmentTime(\google\protobuf\Timestamp $value){
      return $this->_set(8, $value);
    }
    
    /**
     * Check if <order> has a value
     *
     * @return boolean
     */
    public function hasOrder(){
      return $this->_has(9);
    }
    
    /**
     * Clear <order> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function clearOrder(){
      return $this->_clear(9);
    }
    
    /**
     * Get <order> value
     *
     * @return int - \google\devtools\clouderrorreporting\v1beta1\ErrorGroupOrder
     */
    public function getOrder(){
      return $this->_get(9);
    }
    
    /**
     * Set <order> value
     *
     * @param int - \google\devtools\clouderrorreporting\v1beta1\ErrorGroupOrder $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function setOrder( $value){
      return $this->_set(9, $value);
    }
    
    /**
     * Check if <page_size> has a value
     *
     * @return boolean
     */
    public function hasPageSize(){
      return $this->_has(11);
    }
    
    /**
     * Clear <page_size> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function clearPageSize(){
      return $this->_clear(11);
    }
    
    /**
     * Get <page_size> value
     *
     * @return int
     */
    public function getPageSize(){
      return $this->_get(11);
    }
    
    /**
     * Set <page_size> value
     *
     * @param int $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function setPageSize( $value){
      return $this->_set(11, $value);
    }
    
    /**
     * Check if <page_token> has a value
     *
     * @return boolean
     */
    public function hasPageToken(){
      return $this->_has(12);
    }
    
    /**
     * Clear <page_token> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function clearPageToken(){
      return $this->_clear(12);
    }
    
    /**
     * Get <page_token> value
     *
     * @return string
     */
    public function getPageToken(){
      return $this->_get(12);
    }
    
    /**
     * Set <page_token> value
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest
     */
    public function setPageToken( $value){
      return $this->_set(12, $value);
    }
  }
}

namespace google\devtools\clouderrorreporting\v1beta1 {

  class ListGroupStatsResponse extends \DrSlump\Protobuf\Message {

    /**  @var \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats[]  */
    public $error_group_stats = array();
    
    /**  @var string */
    public $next_page_token = null;
    
    /**  @var \google\protobuf\Timestamp */
    public $time_range_begin = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.devtools.clouderrorreporting.v1beta1.ListGroupStatsResponse');

      // REPEATED MESSAGE error_group_stats = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "error_group_stats";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats';
      $descriptor->addField($f);

      // OPTIONAL STRING next_page_token = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "next_page_token";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE time_range_begin = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "time_range_begin";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\protobuf\Timestamp';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <error_group_stats> has a value
     *
     * @return boolean
     */
    public function hasErrorGroupStats(){
      return $this->_has(1);
    }
    
    /**
     * Clear <error_group_stats> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsResponse
     */
    public function clearErrorGroupStats(){
      return $this->_clear(1);
    }
    
    /**
     * Get <error_group_stats> value
     *
     * @param int $idx
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function getErrorGroupStats($idx = NULL){
      return $this->_get(1, $idx);
    }
    
    /**
     * Set <error_group_stats> value
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsResponse
     */
    public function setErrorGroupStats(\google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats $value, $idx = NULL){
      return $this->_set(1, $value, $idx);
    }
    
    /**
     * Get all elements of <error_group_stats>
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats[]
     */
    public function getErrorGroupStatsList(){
     return $this->_get(1);
    }
    
    /**
     * Add a new element to <error_group_stats>
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsResponse
     */
    public function addErrorGroupStats(\google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats $value){
     return $this->_add(1, $value);
    }
    
    /**
     * Check if <next_page_token> has a value
     *
     * @return boolean
     */
    public function hasNextPageToken(){
      return $this->_has(2);
    }
    
    /**
     * Clear <next_page_token> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsResponse
     */
    public function clearNextPageToken(){
      return $this->_clear(2);
    }
    
    /**
     * Get <next_page_token> value
     *
     * @return string
     */
    public function getNextPageToken(){
      return $this->_get(2);
    }
    
    /**
     * Set <next_page_token> value
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsResponse
     */
    public function setNextPageToken( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <time_range_begin> has a value
     *
     * @return boolean
     */
    public function hasTimeRangeBegin(){
      return $this->_has(4);
    }
    
    /**
     * Clear <time_range_begin> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsResponse
     */
    public function clearTimeRangeBegin(){
      return $this->_clear(4);
    }
    
    /**
     * Get <time_range_begin> value
     *
     * @return \google\protobuf\Timestamp
     */
    public function getTimeRangeBegin(){
      return $this->_get(4);
    }
    
    /**
     * Set <time_range_begin> value
     *
     * @param \google\protobuf\Timestamp $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListGroupStatsResponse
     */
    public function setTimeRangeBegin(\google\protobuf\Timestamp $value){
      return $this->_set(4, $value);
    }
  }
}

namespace google\devtools\clouderrorreporting\v1beta1 {

  class ErrorGroupStats extends \DrSlump\Protobuf\Message {

    /**  @var \google\devtools\clouderrorreporting\v1beta1\ErrorGroup */
    public $group = null;
    
    /**  @var int */
    public $count = null;
    
    /**  @var int */
    public $affected_users_count = null;
    
    /**  @var \google\devtools\clouderrorreporting\v1beta1\TimedCount[]  */
    public $timed_counts = array();
    
    /**  @var \google\protobuf\Timestamp */
    public $first_seen_time = null;
    
    /**  @var \google\protobuf\Timestamp */
    public $last_seen_time = null;
    
    /**  @var \google\devtools\clouderrorreporting\v1beta1\ServiceContext[]  */
    public $affected_services = array();
    
    /**  @var int */
    public $num_affected_services = null;
    
    /**  @var \google\devtools\clouderrorreporting\v1beta1\ErrorEvent */
    public $representative = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.devtools.clouderrorreporting.v1beta1.ErrorGroupStats');

      // OPTIONAL MESSAGE group = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "group";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\ErrorGroup';
      $descriptor->addField($f);

      // OPTIONAL INT64 count = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "count";
      $f->type      = \DrSlump\Protobuf::TYPE_INT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL INT64 affected_users_count = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "affected_users_count";
      $f->type      = \DrSlump\Protobuf::TYPE_INT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED MESSAGE timed_counts = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "timed_counts";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\TimedCount';
      $descriptor->addField($f);

      // OPTIONAL MESSAGE first_seen_time = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "first_seen_time";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\protobuf\Timestamp';
      $descriptor->addField($f);

      // OPTIONAL MESSAGE last_seen_time = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "last_seen_time";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\protobuf\Timestamp';
      $descriptor->addField($f);

      // REPEATED MESSAGE affected_services = 7
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 7;
      $f->name      = "affected_services";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\ServiceContext';
      $descriptor->addField($f);

      // OPTIONAL INT32 num_affected_services = 8
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 8;
      $f->name      = "num_affected_services";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE representative = 9
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 9;
      $f->name      = "representative";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\ErrorEvent';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <group> has a value
     *
     * @return boolean
     */
    public function hasGroup(){
      return $this->_has(1);
    }
    
    /**
     * Clear <group> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function clearGroup(){
      return $this->_clear(1);
    }
    
    /**
     * Get <group> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroup
     */
    public function getGroup(){
      return $this->_get(1);
    }
    
    /**
     * Set <group> value
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\ErrorGroup $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function setGroup(\google\devtools\clouderrorreporting\v1beta1\ErrorGroup $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <count> has a value
     *
     * @return boolean
     */
    public function hasCount(){
      return $this->_has(2);
    }
    
    /**
     * Clear <count> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function clearCount(){
      return $this->_clear(2);
    }
    
    /**
     * Get <count> value
     *
     * @return int
     */
    public function getCount(){
      return $this->_get(2);
    }
    
    /**
     * Set <count> value
     *
     * @param int $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function setCount( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <affected_users_count> has a value
     *
     * @return boolean
     */
    public function hasAffectedUsersCount(){
      return $this->_has(3);
    }
    
    /**
     * Clear <affected_users_count> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function clearAffectedUsersCount(){
      return $this->_clear(3);
    }
    
    /**
     * Get <affected_users_count> value
     *
     * @return int
     */
    public function getAffectedUsersCount(){
      return $this->_get(3);
    }
    
    /**
     * Set <affected_users_count> value
     *
     * @param int $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function setAffectedUsersCount( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <timed_counts> has a value
     *
     * @return boolean
     */
    public function hasTimedCounts(){
      return $this->_has(4);
    }
    
    /**
     * Clear <timed_counts> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function clearTimedCounts(){
      return $this->_clear(4);
    }
    
    /**
     * Get <timed_counts> value
     *
     * @param int $idx
     * @return \google\devtools\clouderrorreporting\v1beta1\TimedCount
     */
    public function getTimedCounts($idx = NULL){
      return $this->_get(4, $idx);
    }
    
    /**
     * Set <timed_counts> value
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\TimedCount $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function setTimedCounts(\google\devtools\clouderrorreporting\v1beta1\TimedCount $value, $idx = NULL){
      return $this->_set(4, $value, $idx);
    }
    
    /**
     * Get all elements of <timed_counts>
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\TimedCount[]
     */
    public function getTimedCountsList(){
     return $this->_get(4);
    }
    
    /**
     * Add a new element to <timed_counts>
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\TimedCount $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function addTimedCounts(\google\devtools\clouderrorreporting\v1beta1\TimedCount $value){
     return $this->_add(4, $value);
    }
    
    /**
     * Check if <first_seen_time> has a value
     *
     * @return boolean
     */
    public function hasFirstSeenTime(){
      return $this->_has(5);
    }
    
    /**
     * Clear <first_seen_time> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function clearFirstSeenTime(){
      return $this->_clear(5);
    }
    
    /**
     * Get <first_seen_time> value
     *
     * @return \google\protobuf\Timestamp
     */
    public function getFirstSeenTime(){
      return $this->_get(5);
    }
    
    /**
     * Set <first_seen_time> value
     *
     * @param \google\protobuf\Timestamp $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function setFirstSeenTime(\google\protobuf\Timestamp $value){
      return $this->_set(5, $value);
    }
    
    /**
     * Check if <last_seen_time> has a value
     *
     * @return boolean
     */
    public function hasLastSeenTime(){
      return $this->_has(6);
    }
    
    /**
     * Clear <last_seen_time> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function clearLastSeenTime(){
      return $this->_clear(6);
    }
    
    /**
     * Get <last_seen_time> value
     *
     * @return \google\protobuf\Timestamp
     */
    public function getLastSeenTime(){
      return $this->_get(6);
    }
    
    /**
     * Set <last_seen_time> value
     *
     * @param \google\protobuf\Timestamp $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function setLastSeenTime(\google\protobuf\Timestamp $value){
      return $this->_set(6, $value);
    }
    
    /**
     * Check if <affected_services> has a value
     *
     * @return boolean
     */
    public function hasAffectedServices(){
      return $this->_has(7);
    }
    
    /**
     * Clear <affected_services> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function clearAffectedServices(){
      return $this->_clear(7);
    }
    
    /**
     * Get <affected_services> value
     *
     * @param int $idx
     * @return \google\devtools\clouderrorreporting\v1beta1\ServiceContext
     */
    public function getAffectedServices($idx = NULL){
      return $this->_get(7, $idx);
    }
    
    /**
     * Set <affected_services> value
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\ServiceContext $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function setAffectedServices(\google\devtools\clouderrorreporting\v1beta1\ServiceContext $value, $idx = NULL){
      return $this->_set(7, $value, $idx);
    }
    
    /**
     * Get all elements of <affected_services>
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ServiceContext[]
     */
    public function getAffectedServicesList(){
     return $this->_get(7);
    }
    
    /**
     * Add a new element to <affected_services>
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\ServiceContext $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function addAffectedServices(\google\devtools\clouderrorreporting\v1beta1\ServiceContext $value){
     return $this->_add(7, $value);
    }
    
    /**
     * Check if <num_affected_services> has a value
     *
     * @return boolean
     */
    public function hasNumAffectedServices(){
      return $this->_has(8);
    }
    
    /**
     * Clear <num_affected_services> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function clearNumAffectedServices(){
      return $this->_clear(8);
    }
    
    /**
     * Get <num_affected_services> value
     *
     * @return int
     */
    public function getNumAffectedServices(){
      return $this->_get(8);
    }
    
    /**
     * Set <num_affected_services> value
     *
     * @param int $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function setNumAffectedServices( $value){
      return $this->_set(8, $value);
    }
    
    /**
     * Check if <representative> has a value
     *
     * @return boolean
     */
    public function hasRepresentative(){
      return $this->_has(9);
    }
    
    /**
     * Clear <representative> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function clearRepresentative(){
      return $this->_clear(9);
    }
    
    /**
     * Get <representative> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorEvent
     */
    public function getRepresentative(){
      return $this->_get(9);
    }
    
    /**
     * Set <representative> value
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\ErrorEvent $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorGroupStats
     */
    public function setRepresentative(\google\devtools\clouderrorreporting\v1beta1\ErrorEvent $value){
      return $this->_set(9, $value);
    }
  }
}

namespace google\devtools\clouderrorreporting\v1beta1 {

  class TimedCount extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $count = null;
    
    /**  @var \google\protobuf\Timestamp */
    public $start_time = null;
    
    /**  @var \google\protobuf\Timestamp */
    public $end_time = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.devtools.clouderrorreporting.v1beta1.TimedCount');

      // OPTIONAL INT64 count = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "count";
      $f->type      = \DrSlump\Protobuf::TYPE_INT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE start_time = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "start_time";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\protobuf\Timestamp';
      $descriptor->addField($f);

      // OPTIONAL MESSAGE end_time = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "end_time";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\protobuf\Timestamp';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <count> has a value
     *
     * @return boolean
     */
    public function hasCount(){
      return $this->_has(1);
    }
    
    /**
     * Clear <count> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\TimedCount
     */
    public function clearCount(){
      return $this->_clear(1);
    }
    
    /**
     * Get <count> value
     *
     * @return int
     */
    public function getCount(){
      return $this->_get(1);
    }
    
    /**
     * Set <count> value
     *
     * @param int $value
     * @return \google\devtools\clouderrorreporting\v1beta1\TimedCount
     */
    public function setCount( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <start_time> has a value
     *
     * @return boolean
     */
    public function hasStartTime(){
      return $this->_has(2);
    }
    
    /**
     * Clear <start_time> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\TimedCount
     */
    public function clearStartTime(){
      return $this->_clear(2);
    }
    
    /**
     * Get <start_time> value
     *
     * @return \google\protobuf\Timestamp
     */
    public function getStartTime(){
      return $this->_get(2);
    }
    
    /**
     * Set <start_time> value
     *
     * @param \google\protobuf\Timestamp $value
     * @return \google\devtools\clouderrorreporting\v1beta1\TimedCount
     */
    public function setStartTime(\google\protobuf\Timestamp $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <end_time> has a value
     *
     * @return boolean
     */
    public function hasEndTime(){
      return $this->_has(3);
    }
    
    /**
     * Clear <end_time> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\TimedCount
     */
    public function clearEndTime(){
      return $this->_clear(3);
    }
    
    /**
     * Get <end_time> value
     *
     * @return \google\protobuf\Timestamp
     */
    public function getEndTime(){
      return $this->_get(3);
    }
    
    /**
     * Set <end_time> value
     *
     * @param \google\protobuf\Timestamp $value
     * @return \google\devtools\clouderrorreporting\v1beta1\TimedCount
     */
    public function setEndTime(\google\protobuf\Timestamp $value){
      return $this->_set(3, $value);
    }
  }
}

namespace google\devtools\clouderrorreporting\v1beta1 {

  class ListEventsRequest extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $project_name = null;
    
    /**  @var string */
    public $group_id = null;
    
    /**  @var \google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter */
    public $service_filter = null;
    
    /**  @var \google\devtools\clouderrorreporting\v1beta1\QueryTimeRange */
    public $time_range = null;
    
    /**  @var int */
    public $page_size = null;
    
    /**  @var string */
    public $page_token = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.devtools.clouderrorreporting.v1beta1.ListEventsRequest');

      // OPTIONAL STRING project_name = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "project_name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING group_id = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "group_id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE service_filter = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "service_filter";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter';
      $descriptor->addField($f);

      // OPTIONAL MESSAGE time_range = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "time_range";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\QueryTimeRange';
      $descriptor->addField($f);

      // OPTIONAL INT32 page_size = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "page_size";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING page_token = 7
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 7;
      $f->name      = "page_token";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <project_name> has a value
     *
     * @return boolean
     */
    public function hasProjectName(){
      return $this->_has(1);
    }
    
    /**
     * Clear <project_name> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsRequest
     */
    public function clearProjectName(){
      return $this->_clear(1);
    }
    
    /**
     * Get <project_name> value
     *
     * @return string
     */
    public function getProjectName(){
      return $this->_get(1);
    }
    
    /**
     * Set <project_name> value
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsRequest
     */
    public function setProjectName( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <group_id> has a value
     *
     * @return boolean
     */
    public function hasGroupId(){
      return $this->_has(2);
    }
    
    /**
     * Clear <group_id> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsRequest
     */
    public function clearGroupId(){
      return $this->_clear(2);
    }
    
    /**
     * Get <group_id> value
     *
     * @return string
     */
    public function getGroupId(){
      return $this->_get(2);
    }
    
    /**
     * Set <group_id> value
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsRequest
     */
    public function setGroupId( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <service_filter> has a value
     *
     * @return boolean
     */
    public function hasServiceFilter(){
      return $this->_has(3);
    }
    
    /**
     * Clear <service_filter> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsRequest
     */
    public function clearServiceFilter(){
      return $this->_clear(3);
    }
    
    /**
     * Get <service_filter> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter
     */
    public function getServiceFilter(){
      return $this->_get(3);
    }
    
    /**
     * Set <service_filter> value
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsRequest
     */
    public function setServiceFilter(\google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <time_range> has a value
     *
     * @return boolean
     */
    public function hasTimeRange(){
      return $this->_has(4);
    }
    
    /**
     * Clear <time_range> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsRequest
     */
    public function clearTimeRange(){
      return $this->_clear(4);
    }
    
    /**
     * Get <time_range> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\QueryTimeRange
     */
    public function getTimeRange(){
      return $this->_get(4);
    }
    
    /**
     * Set <time_range> value
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\QueryTimeRange $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsRequest
     */
    public function setTimeRange(\google\devtools\clouderrorreporting\v1beta1\QueryTimeRange $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <page_size> has a value
     *
     * @return boolean
     */
    public function hasPageSize(){
      return $this->_has(6);
    }
    
    /**
     * Clear <page_size> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsRequest
     */
    public function clearPageSize(){
      return $this->_clear(6);
    }
    
    /**
     * Get <page_size> value
     *
     * @return int
     */
    public function getPageSize(){
      return $this->_get(6);
    }
    
    /**
     * Set <page_size> value
     *
     * @param int $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsRequest
     */
    public function setPageSize( $value){
      return $this->_set(6, $value);
    }
    
    /**
     * Check if <page_token> has a value
     *
     * @return boolean
     */
    public function hasPageToken(){
      return $this->_has(7);
    }
    
    /**
     * Clear <page_token> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsRequest
     */
    public function clearPageToken(){
      return $this->_clear(7);
    }
    
    /**
     * Get <page_token> value
     *
     * @return string
     */
    public function getPageToken(){
      return $this->_get(7);
    }
    
    /**
     * Set <page_token> value
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsRequest
     */
    public function setPageToken( $value){
      return $this->_set(7, $value);
    }
  }
}

namespace google\devtools\clouderrorreporting\v1beta1 {

  class ListEventsResponse extends \DrSlump\Protobuf\Message {

    /**  @var \google\devtools\clouderrorreporting\v1beta1\ErrorEvent[]  */
    public $error_events = array();
    
    /**  @var string */
    public $next_page_token = null;
    
    /**  @var \google\protobuf\Timestamp */
    public $time_range_begin = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.devtools.clouderrorreporting.v1beta1.ListEventsResponse');

      // REPEATED MESSAGE error_events = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "error_events";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\ErrorEvent';
      $descriptor->addField($f);

      // OPTIONAL STRING next_page_token = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "next_page_token";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE time_range_begin = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "time_range_begin";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\protobuf\Timestamp';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <error_events> has a value
     *
     * @return boolean
     */
    public function hasErrorEvents(){
      return $this->_has(1);
    }
    
    /**
     * Clear <error_events> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsResponse
     */
    public function clearErrorEvents(){
      return $this->_clear(1);
    }
    
    /**
     * Get <error_events> value
     *
     * @param int $idx
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorEvent
     */
    public function getErrorEvents($idx = NULL){
      return $this->_get(1, $idx);
    }
    
    /**
     * Set <error_events> value
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\ErrorEvent $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsResponse
     */
    public function setErrorEvents(\google\devtools\clouderrorreporting\v1beta1\ErrorEvent $value, $idx = NULL){
      return $this->_set(1, $value, $idx);
    }
    
    /**
     * Get all elements of <error_events>
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ErrorEvent[]
     */
    public function getErrorEventsList(){
     return $this->_get(1);
    }
    
    /**
     * Add a new element to <error_events>
     *
     * @param \google\devtools\clouderrorreporting\v1beta1\ErrorEvent $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsResponse
     */
    public function addErrorEvents(\google\devtools\clouderrorreporting\v1beta1\ErrorEvent $value){
     return $this->_add(1, $value);
    }
    
    /**
     * Check if <next_page_token> has a value
     *
     * @return boolean
     */
    public function hasNextPageToken(){
      return $this->_has(2);
    }
    
    /**
     * Clear <next_page_token> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsResponse
     */
    public function clearNextPageToken(){
      return $this->_clear(2);
    }
    
    /**
     * Get <next_page_token> value
     *
     * @return string
     */
    public function getNextPageToken(){
      return $this->_get(2);
    }
    
    /**
     * Set <next_page_token> value
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsResponse
     */
    public function setNextPageToken( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <time_range_begin> has a value
     *
     * @return boolean
     */
    public function hasTimeRangeBegin(){
      return $this->_has(4);
    }
    
    /**
     * Clear <time_range_begin> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsResponse
     */
    public function clearTimeRangeBegin(){
      return $this->_clear(4);
    }
    
    /**
     * Get <time_range_begin> value
     *
     * @return \google\protobuf\Timestamp
     */
    public function getTimeRangeBegin(){
      return $this->_get(4);
    }
    
    /**
     * Set <time_range_begin> value
     *
     * @param \google\protobuf\Timestamp $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ListEventsResponse
     */
    public function setTimeRangeBegin(\google\protobuf\Timestamp $value){
      return $this->_set(4, $value);
    }
  }
}

namespace google\devtools\clouderrorreporting\v1beta1\QueryTimeRange {

  class Period extends \DrSlump\Protobuf\Enum {
    const PERIOD_UNSPECIFIED = 0;
    const PERIOD_1_HOUR = 1;
    const PERIOD_6_HOURS = 2;
    const PERIOD_1_DAY = 3;
    const PERIOD_1_WEEK = 4;
    const PERIOD_30_DAYS = 5;
  }
}
namespace google\devtools\clouderrorreporting\v1beta1 {

  class QueryTimeRange extends \DrSlump\Protobuf\Message {

    /**  @var int - \google\devtools\clouderrorreporting\v1beta1\QueryTimeRange\Period */
    public $period = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.devtools.clouderrorreporting.v1beta1.QueryTimeRange');

      // OPTIONAL ENUM period = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "period";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\devtools\clouderrorreporting\v1beta1\QueryTimeRange\Period';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <period> has a value
     *
     * @return boolean
     */
    public function hasPeriod(){
      return $this->_has(1);
    }
    
    /**
     * Clear <period> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\QueryTimeRange
     */
    public function clearPeriod(){
      return $this->_clear(1);
    }
    
    /**
     * Get <period> value
     *
     * @return int - \google\devtools\clouderrorreporting\v1beta1\QueryTimeRange\Period
     */
    public function getPeriod(){
      return $this->_get(1);
    }
    
    /**
     * Set <period> value
     *
     * @param int - \google\devtools\clouderrorreporting\v1beta1\QueryTimeRange\Period $value
     * @return \google\devtools\clouderrorreporting\v1beta1\QueryTimeRange
     */
    public function setPeriod( $value){
      return $this->_set(1, $value);
    }
  }
}

namespace google\devtools\clouderrorreporting\v1beta1 {

  class ServiceContextFilter extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $service = null;
    
    /**  @var string */
    public $version = null;
    
    /**  @var string */
    public $resource_type = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.devtools.clouderrorreporting.v1beta1.ServiceContextFilter');

      // OPTIONAL STRING service = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "service";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING version = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "version";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING resource_type = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "resource_type";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <service> has a value
     *
     * @return boolean
     */
    public function hasService(){
      return $this->_has(2);
    }
    
    /**
     * Clear <service> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter
     */
    public function clearService(){
      return $this->_clear(2);
    }
    
    /**
     * Get <service> value
     *
     * @return string
     */
    public function getService(){
      return $this->_get(2);
    }
    
    /**
     * Set <service> value
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter
     */
    public function setService( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <version> has a value
     *
     * @return boolean
     */
    public function hasVersion(){
      return $this->_has(3);
    }
    
    /**
     * Clear <version> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter
     */
    public function clearVersion(){
      return $this->_clear(3);
    }
    
    /**
     * Get <version> value
     *
     * @return string
     */
    public function getVersion(){
      return $this->_get(3);
    }
    
    /**
     * Set <version> value
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter
     */
    public function setVersion( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <resource_type> has a value
     *
     * @return boolean
     */
    public function hasResourceType(){
      return $this->_has(4);
    }
    
    /**
     * Clear <resource_type> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter
     */
    public function clearResourceType(){
      return $this->_clear(4);
    }
    
    /**
     * Get <resource_type> value
     *
     * @return string
     */
    public function getResourceType(){
      return $this->_get(4);
    }
    
    /**
     * Set <resource_type> value
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\ServiceContextFilter
     */
    public function setResourceType( $value){
      return $this->_set(4, $value);
    }
  }
}

namespace google\devtools\clouderrorreporting\v1beta1 {

  class DeleteEventsRequest extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $project_name = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.devtools.clouderrorreporting.v1beta1.DeleteEventsRequest');

      // OPTIONAL STRING project_name = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "project_name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <project_name> has a value
     *
     * @return boolean
     */
    public function hasProjectName(){
      return $this->_has(1);
    }
    
    /**
     * Clear <project_name> value
     *
     * @return \google\devtools\clouderrorreporting\v1beta1\DeleteEventsRequest
     */
    public function clearProjectName(){
      return $this->_clear(1);
    }
    
    /**
     * Get <project_name> value
     *
     * @return string
     */
    public function getProjectName(){
      return $this->_get(1);
    }
    
    /**
     * Set <project_name> value
     *
     * @param string $value
     * @return \google\devtools\clouderrorreporting\v1beta1\DeleteEventsRequest
     */
    public function setProjectName( $value){
      return $this->_set(1, $value);
    }
  }
}

namespace google\devtools\clouderrorreporting\v1beta1 {

  class DeleteEventsResponse extends \DrSlump\Protobuf\Message {


    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.devtools.clouderrorreporting.v1beta1.DeleteEventsResponse');

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }
  }
}

namespace google\devtools\clouderrorreporting\v1beta1 {

  class ErrorStatsServiceGrpcClient extends \Grpc\BaseStub {

    public function __construct($hostname, $opts) {
      parent::__construct($hostname, $opts);
    }
    /**
     * @param google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest $input
     */
    public function ListGroupStats(\google\devtools\clouderrorreporting\v1beta1\ListGroupStatsRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/google.devtools.clouderrorreporting.v1beta1.ErrorStatsService/ListGroupStats', $argument, '\google\devtools\clouderrorreporting\v1beta1\ListGroupStatsResponse::deserialize', $metadata, $options);
    }
    /**
     * @param google\devtools\clouderrorreporting\v1beta1\ListEventsRequest $input
     */
    public function ListEvents(\google\devtools\clouderrorreporting\v1beta1\ListEventsRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/google.devtools.clouderrorreporting.v1beta1.ErrorStatsService/ListEvents', $argument, '\google\devtools\clouderrorreporting\v1beta1\ListEventsResponse::deserialize', $metadata, $options);
    }
    /**
     * @param google\devtools\clouderrorreporting\v1beta1\DeleteEventsRequest $input
     */
    public function DeleteEvents(\google\devtools\clouderrorreporting\v1beta1\DeleteEventsRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/google.devtools.clouderrorreporting.v1beta1.ErrorStatsService/DeleteEvents', $argument, '\google\devtools\clouderrorreporting\v1beta1\DeleteEventsResponse::deserialize', $metadata, $options);
    }
  }
}
