<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Cloud repository for storing output.
 *
 * Generated from protobuf message <code>google.privacy.dlp.v2beta1.OutputStorageConfig</code>
 */
class OutputStorageConfig extends \Google\Protobuf\Internal\Message
{
    protected $type;

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * The path to a Google Cloud Storage location to store output.
     *
     * Generated from protobuf field <code>.google.privacy.dlp.v2beta1.CloudStoragePath storage_path = 2;</code>
     * @return \Google\Privacy\Dlp\V2beta1\CloudStoragePath
     */
    public function getStoragePath()
    {
        return $this->readOneof(2);
    }

    /**
     * The path to a Google Cloud Storage location to store output.
     *
     * Generated from protobuf field <code>.google.privacy.dlp.v2beta1.CloudStoragePath storage_path = 2;</code>
     * @param \Google\Privacy\Dlp\V2beta1\CloudStoragePath $var
     */
    public function setStoragePath(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\CloudStoragePath::class);
        $this->writeOneof(2, $var);
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->whichOneof("type");
    }

}

